### ISSUE TITLE
Removing/Disabling Meteor-Electron

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [rissem/meteor-electron#115]
All is working perfectly for me! I tried this out on an application I'm experimenting with. I just wanted to see if it is possible to now remove/disable this package?

**Comment by wearhere** [comment]
As far as I know you do `meteor remove` as normal, does that not work?

**Comment by Jordan-Eckowitz** [comment]
It does, apologies, I'm new to Meteor. Thanks for the help.

**Comment by wearhere** [comment]
No worries!
