### ISSUE TITLE
quark:electron not found

### ISSUE THREAD

**Issue by sebakerckhof** [rissem/meteor-electron#59]
Hello,

If I want to add the package, I get an error `no such package`
Atmosphere also doesn't show the package: https://atmospherejs.com/?q=electron

...

**Comment by sebakerckhof** [comment]
Okay, now I read `it has not been published to Atmosphere yet.` .. Sorry about that

**Comment by wearhere** [comment]
No trouble!

I'll comment back here when it's been published (no later than 1/21).
