### ISSUE TITLE
Linux support please...

### ISSUE THREAD

**Issue by Rongky** [rissem/meteor-electron#62]
Good day...

Just hoping there will also be support for linux!
and thanks for this awesome package... 
finally, meteor has something for the desktop in online mode..

tnx.

**Comment by wearhere** [comment]
I don't need to support Linux at the moment, but I'd definitely take pull requests for this! A rough sketch of tasks:
- [ ] support building for Linux — see if adding the appropriate platform/arch object to `Meteor.settings.electron.build` just works
- [ ] support setting the app icon on Linux — will need to be handled differently than for Mac/Windows, see https://github.com/maxogden/electron-packager 's README
- [ ] support downloading the Linux app - probably just a matter of parsing the download URL [here](https://github.com/electron-webapps/meteor-electron/blob/master/server/downloadUrls.js#L62) but I don't have a sense of what that looks like (is it an installer like on Windows, or a (zipped form of?) the app itself like on Mac?)
- [ ] support remote updates

On the last note, I've heard that Electron's auto-updater framework doesn't actually support Linux—it's recommended that you update the app just via the system package manager. In that case, I don't know if there's anything for `meteor-electron` to do, I'd just want to document this in its README.
