### ISSUE TITLE
Electron.isFullScreen() in browser throws error

### ISSUE THREAD

**Issue by rdickert** [rissem/meteor-electron#75]
[client/index.js](https://github.com/electron-webapps/meteor-electron/blob/master/client/index.js) attemps to stub out Electron methods that could be inappropriately called from the browser by assigning `_.noop` to them. Unfortunately, Meteor apparently uses an [old version of underscore](https://github.com/meteor/meteor/blob/devel/packages/underscore/underscore.js#L1) that does not support that function, so `Electron.isFullScreen` & similar are undefined, and if you try to call them in the browser, you will get `Uncaught TypeError: Electron.isFullScreen is not a function(…)`.

**Comment by wearhere** [comment]
Thanks @rdickert !
