### ISSUE TITLE
"Auto-update" vs "hot code push" clarification

### ISSUE THREAD

**Issue by pcorey** [rissem/meteor-electron#76]
Hey,

Thanks for this package. It looks like a fantastic solution!

I was hoping to have the differences (if any) between "auto-updates" vs "hot code pushes" clarified a bit. With my local testing, it looks like the Meteor client application can be updates via hot code push, but the documentation makes extensive references to "enabling auto-updates".

Does auto-updating refer to updates to the compiled electron application (the contents of [`/app`](https://github.com/electron-webapps/meteor-electron/tree/master/app)), rather than the Meteor client application? Does hot code push still work for signed and distributed electron executables?

Thanks for your help!

**Comment by wearhere** [comment]
> Does auto-updating refer to updates to the compiled electron application (the contents of /app), rather than the Meteor client application? Does hot code push still work for signed and distributed electron executables?

Yes and yes! You can still update the "web" part of the app, the UI and its backend logic, using hot code push. You just can't update the part of the app that interfaces with the OS without shipping a new version of the app (distributed via auto-updates).

**Comment by wearhere** [comment]
Added a bit to the README, thanks for the suggestion!
