### ISSUE TITLE
Wrong IronRouter version

### ISSUE THREAD

**Issue by alexnault** [rissem/meteor-electron#77]
I get this error after installing the package and starting my Meteor app :

```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: iron:router 0.9.4, was 1.0.12.
   Constraints on package "iron:router":
   * iron:router@0.9.4 <- meson:electron 0.1.3

   To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

=> Your application has errors. Waiting for file change.
```

What exactly should I do? Downgrading caused a lot of issues. Should I pull-request and update iron-router?

**Comment by kartboy16** [comment]
Same issue here.  I used Meteor Kitchen to generate my base code and uses iron:controller which I don't think was available in 0.9.4.  Is the integration of the latest version of iron:router on the horizon or should we just refactor our code?

**Comment by Jayuda** [comment]
+1
any clue for this error ?

**Comment by wearhere** [comment]
Hm I'm surprised this fails! My understanding of the [`api.use`](https://docs.meteor.com/#/full/pack_use) constraint system is that the [current constraint](https://github.com/electron-webapps/meteor-electron/blob/master/package.js#L26) of `"iron:router@0.9.4||1.0.0"` should allow any `1.x.y`.

@anault, if you know how to fix, please submit a PR! This package integrates in a [very minimal way](https://github.com/mixmaxhq/meteor-electron/blob/master/server/serve.js#L3) with Iron Router, I would be surprised if it broke in `1.0.12`.

(But please test that anyway—make sure that `http://localhost:3000/app/latest` returns a response :)

**Comment by phsultan** [comment]
I had the same issue trying to install the 0.1.3 version from atmosphere using `meteor add meson:electron`, which is not compatible with `iron:router 1.x.y`.

Downloading `meson:electron 0.1.4` fixed my problem. Simply clone the repository, and make sure your `PACKAGE_DIRS` variable points to the directory where your various packages are stored, that is, assuming `PACKAGE_DIRS=/Users/me/meteor/local_packages`:

```
cd /Users/me/meteor/local_packages
git clone https://github.com/electron-webapps/meteor-electron.git
```

And then go back to your Meteor application to install meson:electron with `meteor add meson:electron` (a `+` sign will appear next to this package if you type `meteor list` indicating the package was built locally).
